### ISSUE TITLE
Heishamon V5

### ISSUE THREAD

**Issue by Binifada1956** [blb4github/HeishaMon-Rules-with-Opentherm-Thermostat#1]
The new Heishamon V5 is available. What is the current status of your rules? And are they more stable now?

**Comment by blb4github** [comment]
I'm running hw V5 indeed, it's for sure much more stable. I wasn't active a lot due to all instability issues on the old hw version, I'm slowly picking up....

**Comment by blb4github** [comment]
I have just updated my latest (current) rules set: https://github.com/blb4github/HeishaMon-Rules-with-Opentherm-Thermostat/blob/main/HeishaMon_Rules_BlB4.md

**Comment by blb4github** [comment]
Closed as question answered
